const dbSchema = `CREATE TABLE IF NOT EXISTS CONTENT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CID VARCHAR(255),
	NAME VARCHAR(255),
	SIZE VARCHAR(255),
	MINER_ID VARCHAR(255),
	DEAL_DATE VARCHAR(255),
	DEAL_ID VARCHAR(255),
	COMMP_ORIGINAL VARCHAR(255),
	DATE_LAST_CHECK VARCHAR(255),
	COMMP_LATEST VARCHAR(255),
	VERIFY_RESULT VARCHAR(255),
	STATE VARCHAR(255),
	STATUS VARCHAR(255),
	NUMBER_OF_COPIES VARCHAR(255)
);`;

module.exports = {
  dbSchema
};
