const dbSchema = `CREATE TABLE IF NOT EXISTS CONTENT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	UUID VARCHAR,
	CID VARCHAR,
	NAME VARCHAR,
	SIZE VARCHAR,
	SIZE_BYTES BIGINT,
	MINER_ID VARCHAR,
	DEAL_DATE DATETIME,
	DEAL_ID VARCHAR,
	COMMD_ORIGINAL VARCHAR,
	COMMR_ORIGINAL VARCHAR,
	COMMRSTAR_ORIGINAL VARCHAR,
	DATE_LAST_CHECK DATETIME,
	COMMD_LATEST VARCHAR,
	COMMR_LATEST VARCHAR,
	COMMRSTAR_LATEST VARCHAR,
	VERIFY_RESULT VARCHAR,
	STATE VARCHAR,
	STATUS VARCHAR,
	COPY_NUMBER INT,
	DATETIME_STARTED DATETIME,
	UNIQUE(CID, COPY_NUMBER) ON CONFLICT REPLACE
);`;

module.exports = {
  dbSchema
};
